import {database,isAdmin,limit} from '@/lib/shop';
import {integrationStatus,payoutPreview,releaseArtists,reconcileArtists} from '@/lib/integrations';
import {enqueue,kickJobs} from '@/lib/jobs';
import {boundedText} from '@/lib/payment-security';
import {z} from 'zod';
export const dynamic='force-dynamic';
const reply=(d:unknown,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'private, no-store'}});
export async function GET(req:Request){if(!await isAdmin())return reply({error:'Owner access required'},403);try{const db=database();const id=new URL(req.url).searchParams.get('order');if(id){const p=await payoutPreview(id);return reply({allocations:p.allocations,eligibleAt:p.eligibleAt,blocked:p.blocked});}const [artists,assignments,notifications,shipments,earnings]=await Promise.all([
 db.prepare('SELECT * FROM artists ORDER BY name').all(),db.prepare('SELECT * FROM product_artists').all(),db.prepare('SELECT id,order_id,status,state,provider_id,created FROM notifications ORDER BY created DESC LIMIT 30').all(),db.prepare('SELECT order_id,awb,status,checked,delivered FROM shipments ORDER BY checked DESC LIMIT 50').all(),db.prepare("SELECT a.order_id,sum(a.net) AS net,sum(a.gross-a.net) AS commission,o.status,o.payment_method,COALESCE(t.state,'held') AS transfer_state FROM allocations a JOIN orders o ON o.id=a.order_id LEFT JOIN transfers t ON t.order_id=o.id GROUP BY a.order_id ORDER BY o.created DESC LIMIT 100").all()]);return reply({config:integrationStatus(),artists:artists.results,assignments:assignments.results,notifications:notifications.results,shipments:shipments.results,earnings:earnings.results});}catch{return reply({error:'Could not load integrations'},503)}}
export async function POST(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin||!await isAdmin())return reply({error:'Owner access required'},403);try{await limit(req,'integrations',20);const b=JSON.parse(await boundedText(req,4000)),db=database();
 if(b.action==='artist'){const v=z.object({name:z.string().trim().min(2).max(100),account:z.string().regex(/^acc_[a-zA-Z0-9]+$/),commission:z.number().min(0).max(100)}).parse(b);await db.prepare('INSERT INTO artists(id,name,account,commission_bps,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),v.name,v.account,Math.round(v.commission*100),Date.now()).run();}
 else if(b.action==='assign'){const v=z.object({productId:z.string().min(1).max(80),artistId:z.string().uuid()}).parse(b);const exists=await db.prepare('SELECT p.id FROM products p,artists a WHERE p.id=? AND a.id=?').bind(v.productId,v.artistId).first();if(!exists)throw Error('Choose an existing artist and artwork');await db.prepare('INSERT INTO product_artists(product_id,artist_id) VALUES(?,?) ON CONFLICT(product_id) DO UPDATE SET artist_id=excluded.artist_id').bind(v.productId,v.artistId).run();}
 else if(b.action==='shipment'){const v=z.object({orderId:z.string().uuid(),awb:z.string().regex(/^[A-Za-z0-9-]{5,60}$/)}).parse(b);if(!await db.prepare("SELECT id FROM orders WHERE id=? AND status IN ('Confirmed','Shipped')").bind(v.orderId).first())throw Error('Order must be confirmed or shipped');await db.batch([db.prepare("INSERT INTO shipments(order_id,awb) VALUES(?,?) ON CONFLICT(order_id) DO UPDATE SET awb=excluded.awb,checked=0,status='Awaiting tracking',delivered=NULL").bind(v.orderId,v.awb),db.prepare("UPDATE orders SET carrier='Shiprocket',tracking_number=?,tracking_url=? WHERE id=?").bind(v.awb,'https://shiprocket.co/tracking/'+encodeURIComponent(v.awb),v.orderId)]);await enqueue(db,'courier:'+v.orderId+':'+crypto.randomUUID(),'courier',{id:v.orderId});}
 else if(b.action==='sync'){const id=z.string().uuid().parse(b.orderId);await enqueue(db,'courier:'+id+':'+crypto.randomUUID(),'courier',{id});}
 else if(b.action==='release'){await releaseArtists(z.string().uuid().parse(b.orderId));}
 else if(b.action==='reconcile'){await reconcileArtists(z.string().uuid().parse(b.orderId));}
 else throw Error('Unknown action');kickJobs(true);return reply({ok:true});
 }catch(e){return reply({error:e instanceof z.ZodError?'Check the form details':e instanceof Error?e.message:'Could not save integration'},400)}}
