'use client';
import {useEffect,useState} from 'react';
import {money} from '../store';
export default function Integrations({products,orders}:{products:any[];orders:any[]}){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<any>(null);
 async function load(){try{const r=await fetch('/api/integrations');const d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e:any){setError(e.message)}}useEffect(()=>{load()},[]);
 async function act(body:any){setBusy(true);setError('');try{const r=await fetch('/api/integrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error);await load();setPreview(null)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const form=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget))};
 return <section className="integration-panel"><span className="eyebrow">CONNECTED OPERATIONS</span><h2>From your studio to their home.</h2><p>Order emails, courier updates and transparent artist earnings.</p>{error&&<p className="error" role="alert">{error}</p>}{!data?<p>Loading connections…</p>:<><div className="integration-grid">{[['Order email',data.config.email,'Resend · verified sender required'],['Courier tracking',data.config.courier,'Shiprocket · API token required'],['Artist transfers',data.config.payouts,'Razorpay Route · approved linked accounts required']].map(([name,ready,desc])=><article key={String(name)}><h3>{name}</h3><b>{ready?'Configured · provider verification pending':'Setup needed'}</b><p>{desc}</p></article>)}</div><p>Connect credentials through secure site settings. Transfers need an agreed inspection period{data.config.holdDays?` (currently ${data.config.holdDays} days after delivery)`:''}. Email “sent” means accepted by the provider, not inbox delivery. Transfers are to linked accounts, not a guarantee of bank settlement.</p>
 <details><summary>Artists & artwork assignments</summary><form className="studio-form" onSubmit={e=>{const v=form(e);act({action:'artist',...v,commission:Number(v.commission)})}}><div className="form-row"><label>Artist name<input name="name" required minLength={2}/></label><label>Razorpay linked account<input name="account" required placeholder="acc_…" pattern="acc_[a-zA-Z0-9]+"/></label><label>Platform commission (%)<input name="commission" type="number" min="0" max="100" step="0.01" required/></label></div><button className="primary" disabled={busy}>Add artist</button></form><form className="studio-form" onSubmit={e=>act({action:'assign',...form(e)})}><div className="form-row"><label>Artwork<select name="productId" required><option value="">Choose artwork</option>{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Artist<select name="artistId" required><option value="">Choose artist</option>{data.artists.map((a:any)=><option value={a.id} key={a.id}>{a.name} · {a.commission_bps/100}% commission</option>)}</select></label></div><button className="primary" disabled={busy}>Assign for future orders</button></form><p>Existing orders keep their original artist share. Unassigned pieces remain platform sales.</p>{data.assignments.map((a:any)=><p key={a.product_id}>{products.find(p=>p.id===a.product_id)?.name||a.product_id} → {data.artists.find((r:any)=>r.id===a.artist_id)?.name}</p>)}</details>
 <details><summary>Connect a shipment</summary><p>Book the parcel in Shiprocket, then attach its AWB here. Tracking syncs roughly every 15 minutes when the job runner is active. Shipping purchases and labels are managed in Shiprocket.</p><form className="studio-form" onSubmit={e=>act({action:'shipment',...form(e)})}><div className="form-row"><label>Order<select name="orderId" required><option value="">Choose order</option>{orders.filter(o=>['Confirmed','Shipped'].includes(o.status)).map(o=><option key={o.id} value={o.id}>{o.id.slice(0,8).toUpperCase()}</option>)}</select></label><label>Shiprocket AWB<input name="awb" required pattern="[A-Za-z0-9-]{5,60}"/></label></div><button className="primary" disabled={busy}>Connect tracking</button></form>{data.shipments.map((s:any)=><article className="order-card" key={s.order_id}><b>{s.awb} · {s.status}</b><p>{s.checked?'Last checked '+new Date(s.checked).toLocaleString('en-IN'):'Awaiting first sync'}</p><button disabled={busy||!data.config.courier} onClick={()=>act({action:'sync',orderId:s.order_id})}>Refresh tracking</button></article>)}</details>
 <details><summary>Artist earnings & transfers</summary><p>Review each order before releasing funds. Returns and refunded payments block release. COD and Cashfree earnings require separate settlement.</p>{!data.earnings.length&&<p>Artist earnings appear after assigned artwork is ordered.</p>}{data.earnings.map((e:any)=><article className="order-card" key={e.order_id}><h3>{e.order_id.slice(0,8).toUpperCase()} · {money(e.net)} to artists</h3><p>Commission {money(e.commission)} · {e.status} · Transfer {e.transfer_state}</p>{e.transfer_state==='held'?<button disabled={busy} onClick={async()=>{setError('');try{const r=await fetch('/api/integrations?order='+e.order_id);const p:any=await r.json();if(!r.ok)throw Error(p.error);setPreview({...p,id:e.order_id})}catch(x:any){setError(x.message)}}}>Review artist shares</button>:<button disabled={busy} onClick={()=>act({action:'reconcile',orderId:e.order_id})}>Refresh provider status</button>}</article>)}{preview&&<article className="order-card"><h3>Review transfer · {preview.id.slice(0,8).toUpperCase()}</h3>{preview.allocations.map((a:any)=><p key={a.id}>{a.name} · {money(a.net)} · {a.account}</p>)}<p>{preview.blocked||'Eligible for release. This sends funds to the listed linked accounts.'}</p>{preview.eligibleAt&&<p>Inspection period ends {new Date(preview.eligibleAt).toLocaleString('en-IN')}</p>}<button className="primary" disabled={busy||!!preview.blocked} onClick={()=>act({action:'release',orderId:preview.id})}>Release artist funds</button></article>}</details>
 <details><summary>Recent order emails</summary>{!data.notifications.length&&<p>New order updates will appear here.</p>}{data.notifications.map((n:any)=><p key={n.id}>{n.order_id.slice(0,8).toUpperCase()} · {n.status} · {n.state==='disabled'?'Skipped · email not connected':n.state}</p>)}</details></>}</section>
}
