import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
const db={prepare(query){let values=[];return {bind(...v){values=v;return this},async first(){return sql.prepare(query).get(...values)||null},async all(){return {results:sql.prepare(query).all(...values)}},async run(){const r=sql.prepare(query).run(...values);return {meta:{changes:Number(r.changes)}}}}}};
mkdirSync('.sites-runtime',{recursive:true});
for(const name of ['customer','tracking'])writeFileSync(`.sites-runtime/${name}-customer.mjs`,ts.transpileModule(readFileSync('lib/'+name+'.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
const {customerAction,customerData,moderate}=await import('../.sites-runtime/customer-customer.mjs');
const {trackingOrders}=await import('../.sites-runtime/tracking-customer.mjs');
const a='alice',b='bob';const details={name:'Test Buyer',email:'buyer@example.com',phone:'9999999999',address:'123 Test Avenue',city:'Bengaluru',pin:'560001'};
const id=crypto.randomUUID();await customerAction(db,a,null,{action:'address',id,label:'Home',details});await assert.rejects(()=>customerAction(db,b,null,{action:'address',id,label:'Stolen',details}),/could not be saved/);
assert.equal((await customerData(db,b)).addresses.length,0);await customerAction(db,b,null,{action:'delete-address',id});assert.equal((await customerData(db,a)).addresses.length,1);
for(let i=0;i<4;i++)await customerAction(db,a,null,{action:'address',label:'Address '+i,details});await assert.rejects(()=>customerAction(db,a,null,{action:'address',label:'Sixth',details}),/five addresses/);await customerAction(db,a,null,{action:'address',id,label:'Updated',details});assert.equal((await customerData(db,a)).addresses.length,5);
sql.prepare('INSERT INTO products VALUES(?,?,?,?,?,?,?,?,?)').run('art','Test Art','Original art','Description',10000,1,'/art/0.jpg',1,1);
await customerAction(db,a,null,{action:'wishlist',productId:'art',saved:true});await customerAction(db,a,null,{action:'wishlist',productId:'art',saved:true});assert.equal((await customerData(db,a)).wishlist.length,1);assert.equal((await customerData(db,b)).wishlist.length,0);await assert.rejects(()=>customerAction(db,a,null,{action:'wishlist',productId:'missing',saved:true}),/unavailable/);
const orderId=crypto.randomUUID();sql.prepare("INSERT INTO orders(id,session,customer,items,total,status,payment_method,payment_status,created) VALUES(?,?,?,?,?,'Confirmed','cod','Unpaid',?)").run(orderId,'guest',JSON.stringify(details),JSON.stringify([{id:'art',name:'Test Art',qty:1,price:10000}]),10000,1000);
await customerAction(db,a,'guest',{action:'link-orders'});await customerAction(db,b,'guest',{action:'link-orders'});assert.equal((await customerData(db,b)).orders.length,0);assert.equal((await customerData(db,a)).orders.length,1);
assert.equal((await trackingOrders(db,'guest',undefined,Date.now(),b)).orders.length,0);assert.equal((await trackingOrders(db,null,undefined,Date.now(),a)).orders.length,1);assert.equal((await trackingOrders(db,'guest')).orders.length,0);
const review={action:'review',orderId,productId:'art',rating:5,name:'Buyer',title:'Beautiful art',body:'Very pleased with this artwork.'};await assert.rejects(()=>customerAction(db,a,null,review),/delivered purchases/);sql.prepare("UPDATE orders SET status='Delivered' WHERE id=?").run(orderId);await assert.rejects(()=>customerAction(db,b,null,review),/delivered purchases/);await assert.rejects(()=>customerAction(db,a,null,{...review,productId:'not-bought'}),/delivered purchases/);await assert.rejects(()=>customerAction(db,a,null,{...review,rating:6}));
await customerAction(db,a,null,review);const reviewId=orderId+':art';assert.equal(sql.prepare('SELECT status FROM reviews').get().status,'Pending');await moderate(db,{action:'review-status',id:reviewId,status:'Published'});await customerAction(db,a,null,{...review,rating:4});assert.equal(sql.prepare('SELECT count(*) n FROM reviews').get().n,1);assert.equal(sql.prepare('SELECT status FROM reviews').get().status,'Pending');
const request={action:'return',orderId,reason:'Arrived damaged',details:'There is visible damage to the frame.'};await assert.rejects(()=>customerAction(db,b,null,request),/not eligible/);await customerAction(db,a,null,request);await assert.rejects(()=>customerAction(db,a,null,request),/already exists/);
const ret=(await customerData(db,a)).returns[0];await assert.rejects(()=>moderate(db,{action:'return-status',id:ret.id,status:'Closed',reply:'Skipping review'}),/not allowed/);for(const status of ['Approved','Received','Refund pending','Closed'])await moderate(db,{action:'return-status',id:ret.id,status,reply:'Test studio update'});
assert.equal(sql.prepare('SELECT payment_status FROM orders WHERE id=?').get(orderId).payment_status,'Unpaid');assert.equal(sql.prepare('SELECT stock FROM products').get().stock,1);assert.equal((await customerData(db,b)).returns.length,0);
console.log('PASS: account isolation, five-address cap, private wishlist/deduplication, explicit guest order linking, cross-device tracking, delivered-purchase reviews, moderation reset, return ownership/transitions, no automatic refund or stock mutation');
// Exercise the actual account route boundary with mocked platform identity.
writeFileSync('.sites-runtime/customer-security.mjs',ts.transpileModule(readFileSync('lib/payment-security.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
let route=ts.transpileModule(readFileSync('app/api/account/route.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
route=route.replace(/import .* from '@\/app\/chatgpt-auth';/, 'const getChatGPTUser=async()=>globalThis.accountTestUser;').replace(/import .* from '@\/lib\/shop';/,'const database=()=>globalThis.customerDb;const limit=async()=>{};').replace(/import .* from '@\/lib\/payments';/,"const sessionId=()=>null;").replace("'@/lib/customer'","'./customer-customer.mjs'").replace("'@/lib/payment-security'","'./customer-security.mjs'");
writeFileSync('.sites-runtime/customer-route.mjs',route);globalThis.customerDb=db;globalThis.accountTestUser=null;
const accountRoute=await import('../.sites-runtime/customer-route.mjs');
const requestFor=(body,origin='https://shop.test')=>new Request('https://shop.test/api/account',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
assert.equal((await accountRoute.POST(requestFor({action:'wishlist',productId:'art',saved:true}))).status,401);
assert.equal((await accountRoute.POST(requestFor({},'https://evil.test'))).status,403);
const anonymous=await accountRoute.GET(new Request('https://shop.test/api/account'));assert.equal(anonymous.headers.get('Cache-Control'),'private, no-store');assert.deepEqual(await anonymous.json(),{user:null});
globalThis.accountTestUser={userId:a,email:'alice@example.com',fullName:'Alice'};
assert.equal((await accountRoute.POST(requestFor({action:'wishlist',productId:'art',saved:false,userId:b}))).status,200);assert.equal((await customerData(db,a)).wishlist.length,0);
console.log('PASS: actual account API rejects anonymous writes and cross-origin requests, never caches account data, ignores client-supplied identity');
