import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';
import ts from 'typescript';
const sqlite=new DatabaseSync(':memory:');
for(const file of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+file,'utf8'));
function prepare(sql){let values=[];return {bind(...v){values=v;return this},async first(){return sqlite.prepare(sql).get(...values)||null},async all(){return {results:sqlite.prepare(sql).all(...values)}},async run(){return sqlite.prepare(sql).run(...values)}}}
const db={prepare,async batch(statements){sqlite.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const env={RAZORPAY_KEY_ID:'rzp_test_example',RAZORPAY_KEY_SECRET:'test-only-not-a-real-key',RAZORPAY_WEBHOOK_SECRET:'test-only-hook',ENABLE_ONLINE_PAYMENTS:'true'};
globalThis.__paymentTest={database:()=>db,runtime:()=>env};
mkdirSync('.sites-runtime',{recursive:true});
let source=ts.transpileModule(readFileSync('lib/payments.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace("import { database, runtime } from './shop';","const {database,runtime}=globalThis.__paymentTest;");
writeFileSync('.sites-runtime/payment-test-module.mjs',source);
writeFileSync('.sites-runtime/security-test-module.mjs',ts.transpileModule(readFileSync('lib/payment-security.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
const {createCheckout,confirmPayment,expireReservations,reconcileRefund}=await import('../.sites-runtime/payment-test-module.mjs');
const {verifyHmac,boundedText}=await import('../.sites-runtime/security-test-module.mjs');
let counter=0;const payments=new Map();globalThis.fetch=async(url,options)=>{if(url.endsWith('/orders')){const b=JSON.parse(options.body);return Response.json({id:'order_'+(++counter),amount:b.amount,currency:b.currency})}const id=url.split('/').at(-1);assert.ok(payments.has(id),'Expected mocked provider lookup');return Response.json(payments.get(id))};
const customer={name:'Test Customer',email:'test@example.com',phone:'9999999999',address:'Test address, 123 street',city:'Bengaluru',pin:'560001'};
const seed=(id,stock)=>sqlite.prepare('INSERT INTO products VALUES(?,?,?,?,?,?,?,?,?)').run(id,'Artwork','Original art','Description',25000,stock,'image',1,Date.now());
const input=(id)=>({key:crypto.randomUUID(),customer,items:[{id,qty:1}]});
const stock=id=>sqlite.prepare('SELECT stock FROM products WHERE id=?').get(id).stock;
const capture=(a,id)=>payments.set(id,{id,order_id:a.providerOrder,amount:a.amount,currency:'INR',status:'captured'});
seed('a',1);const b=input('a');b.items[0].price=1;const a=await createCheckout(b,'session');assert.equal(a.amount,25000);assert.equal(stock('a'),0);
const same=await createCheckout(b,'session');assert.equal(same.providerOrder,a.providerOrder);assert.equal(stock('a'),0);
await assert.rejects(()=>createCheckout(input('a'),'other'),/unavailable/);
capture(a,'pay_A');await confirmPayment('pay_A');await confirmPayment('pay_A');assert.equal(sqlite.prepare('SELECT count(*) n FROM orders').get().n,1);assert.equal(stock('a'),0);
seed('b',1);const second=await createCheckout(input('b'),'session');sqlite.prepare('UPDATE payment_attempts SET expires=0 WHERE id=?').run(second.id);await expireReservations();await expireReservations();assert.equal(stock('b'),1);
capture(second,'pay_B');await confirmPayment('pay_B');assert.equal(stock('b'),0);assert.equal(sqlite.prepare('SELECT state FROM payment_attempts WHERE id=?').get(second.id).state,'paid');
seed('c',1);const late=await createCheckout(input('c'),'session');sqlite.prepare('UPDATE payment_attempts SET expires=0 WHERE id=?').run(late.id);await expireReservations();await createCheckout(input('c'),'other');capture(late,'pay_C');const flagged=await confirmPayment('pay_C');assert.equal(flagged.state,'refund_required');assert.equal(stock('c'),0);await confirmPayment('pay_C');assert.equal(stock('c'),0);
payments.set('pay_C',{...payments.get('pay_C'),status:'refunded',amount_refunded:25000});await reconcileRefund('pay_C');await reconcileRefund('pay_C');assert.equal(stock('c'),0);assert.equal(sqlite.prepare('SELECT status FROM orders WHERE id=?').get(late.id).status,'Refunded');
seed('d',1);const mismatch=await createCheckout(input('d'),'different');capture(mismatch,'pay_D');payments.get('pay_D').amount=1;await assert.rejects(()=>confirmPayment('pay_D'),/mismatch/);
const secret='signature-test';const payload='order_example|pay_example';const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload))).toString('hex');assert.equal(await verifyHmac(payload,sig,secret),true);assert.equal(await verifyHmac(payload+'tampered',sig,secret),false);assert.equal(await verifyHmac(payload,'invalid',secret),false);
await assert.rejects(()=>boundedText(new Request('https://example.com',{method:'POST',body:'123456'}),5),/too large/);
console.log('PASS: server pricing, duplicate create/capture, stock limits, expiry idempotency, late capture/reallocation, refund reconciliation, amount checks, HMAC tampering, body limits');
