'use client';
import {useEffect,useState} from 'react';
import {Package,ArrowLeft,RefreshCw} from 'lucide-react';
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n/100);
export default function Orders(){
 const [orders,setOrders]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[next,setNext]=useState<number|null>(null),[searched,setSearched]=useState(false);
 async function load(before?:number){setBusy(true);setError('');try{const r=await fetch('/api/orders'+(before?'?before='+before:''));const d:any=await r.json();if(!r.ok)throw Error(d.error);setOrders(old=>before?[...old,...d.orders]:d.orders);setNext(d.nextBefore);setSearched(false)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function find(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const form=new FormData(e.currentTarget);const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:String(form.get('id')).trim(),email:form.get('email')})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setOrders(d.orders);setNext(null);setSearched(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <main className="tracking-page"><a href="/" className="back"><ArrowLeft size={16}/> Back to the collection</a><a href="/account" className="account-orders-link">Manage purchases, reviews & returns ↗</a><span className="eyebrow">FROM THE STUDIO TO YOU</span><h1>Your orders.</h1><p>Follow your artwork’s journey. Status updates are supplied by the studio.</p><div className="tracking-layout"><section aria-label="Order history"><button className="back" disabled={busy} onClick={()=>load()}><RefreshCw size={16}/> {busy?'Loading…':searched?'Show this browser’s orders':'Refresh orders'}</button>{error&&<p className="error" role="alert">{error}</p>}{!orders.length&&!busy&&<div className="empty"><Package size={36}/><h2>No orders here yet.</h2><p>Signed-in purchases and guest orders from this browser appear here. Use your full order reference and checkout email to find an order placed elsewhere.</p></div>}{orders.map(o=><article className="order-card" key={o.id}><div className="tracking-title"><h2>{o.status}</h2><strong>{money(o.total)}</strong></div><p className="order-reference">Reference: {o.id}</p><p>{new Date(o.created).toLocaleString('en-IN')} · Payment: {o.paymentStatus}</p><ul>{o.items.map((i:any,n:number)=><li key={n}>{i.name} × {i.qty}</li>)}</ul>{o.events.length>0?<ol className="order-timeline">{o.events.map((event:any,i:number)=><li key={i}><strong>{event.status}</strong><time>{new Date(event.created).toLocaleString('en-IN')}</time></li>)}</ol>:<p>Earlier history is unavailable for this order. Current status: {o.status}.</p>}{o.trackingNumber&&<div className="shipment-details"><strong>{o.carrier||'Courier'}</strong><p>Tracking number: {o.trackingNumber}</p>{o.trackingUrl&&<a href={o.trackingUrl} target="_blank" rel="noopener noreferrer">Track with the courier ↗</a>}</div>}{o.status==='Refund required'&&<p className="checkout-note">Your payment needs a refund review. Contact the studio with the reference above.</p>}</article>)}{next&&<button className="primary" disabled={busy} onClick={()=>load(next)}>Load older orders</button>}</section><aside><form className="studio-form tracking-find" onSubmit={find}><h2>Find an order</h2><p>Enter the complete reference shown after checkout.</p><label>Full order reference<input name="id" required maxLength={36} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"/></label><label>Checkout email<input name="email" type="email" autoComplete="email" required maxLength={150}/></label><button className="primary" disabled={busy}>Find my order</button><small>Keep your order reference private.</small></form></aside></div></main>
}
