import {database,runtime} from './shop';
import {gateway} from './payments';
import {enqueue} from './job-queue';
export function integrationStatus(){const e=runtime();return {email:!!(e.RESEND_API_KEY&&e.EMAIL_FROM&&e.ENABLE_EMAIL==='true'),courier:!!e.SHIPROCKET_TOKEN,payouts:!!(e.ENABLE_ARTIST_TRANSFERS==='true'&&e.RAZORPAY_KEY_ID&&e.RAZORPAY_KEY_SECRET&&Number(e.ARTIST_HOLD_DAYS)>=1),holdDays:Number(e.ARTIST_HOLD_DAYS)||null};}
export function publicOrigin(){const raw=String(runtime().PUBLIC_SITE_URL||'https://artelier-saransh.ethanhuntss.chatgpt.site');const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password)throw Error('Invalid public site URL');return u.origin;}
// Only new events enter the outbox. Disabled email is recorded, never replayed on activation.
export async function scheduleIntegrations(){const db=database();const cfg=integrationStatus();
 if(!cfg.email)await db.prepare("UPDATE notifications SET state='disabled' WHERE state='pending'").run();
 else {const rows=(await db.prepare("SELECT id FROM notifications WHERE state='pending' ORDER BY created LIMIT 20").all<any>()).results;for(const n of rows)await enqueue(db,'email:'+n.id,'email',{id:n.id});}
 if(cfg.courier){const rows=(await db.prepare("SELECT s.order_id FROM shipments s JOIN orders o ON o.id=s.order_id WHERE s.checked<? AND s.delivered IS NULL AND o.status NOT IN ('Refunded','Refund required') ORDER BY s.checked LIMIT 10").bind(Date.now()-15*60000).all<any>()).results;for(const s of rows)await enqueue(db,'courier:'+s.order_id+':'+Math.floor(Date.now()/900000),'courier',{id:s.order_id});}
}
export async function sendOrderEmail(id:string){const db=database();let n=await db.prepare('SELECT * FROM notifications WHERE id=?').bind(id).first<any>();if(!n||['sent','disabled','review'].includes(n.state))return;
 if(!integrationStatus().email){await db.prepare("UPDATE notifications SET state='disabled' WHERE id=?").bind(id).run();return;}
 // Resend deduplicates for 24h. Stop retrying before that window expires.
 if(n.first_attempt&&Date.now()-n.first_attempt>23*3600000){await db.prepare("UPDATE notifications SET state='review' WHERE id=?").bind(id).run();return;}
 if(!n.payload){const c=JSON.parse(n.customer);const payload=JSON.stringify({from:runtime().EMAIL_FROM,to:[c.email],subject:`Artelier order ${n.order_id.slice(0,8).toUpperCase()} · ${n.status}`,text:`Hello ${c.name},\n\nYour Artelier order ${n.order_id} is now ${n.status}.\n\nView your order at ${publicOrigin()}/orders using your order reference and email.\n\nThank you,\nArtelier`});await db.prepare('UPDATE notifications SET payload=?,first_attempt=? WHERE id=? AND payload IS NULL').bind(payload,Date.now(),id).run();n=await db.prepare('SELECT * FROM notifications WHERE id=?').bind(id).first<any>();}
 const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+runtime().RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':'artelier/'+id},body:n.payload,signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Email provider unavailable');const result:any=await r.json();if(!result.id)throw Error('Email provider response incomplete');await db.prepare("UPDATE notifications SET state='sent',provider_id=? WHERE id=?").bind(result.id,id).run();
}
export async function syncShipment(id:string){const db=database(),s=await db.prepare('SELECT * FROM shipments WHERE order_id=?').bind(id).first<any>();if(!s||!integrationStatus().courier)return;
 const r=await fetch('https://apiv2.shiprocket.in/v1/external/courier/track/awb/'+encodeURIComponent(s.awb),{headers:{Authorization:'Bearer '+runtime().SHIPROCKET_TOKEN},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Courier provider unavailable');const data:any=await r.json();const t=data.tracking_data;const row=t?.shipment_track?.[0];if(!row||String(row.awb_code)!==s.awb)throw Error('Courier tracking mismatch');const code=Number(t.shipment_status);const delivered=code===7;const status=String(row.current_status||'Tracking updated').slice(0,100);const now=Date.now();
 await db.batch([db.prepare('UPDATE shipments SET status=CASE WHEN delivered IS NULL THEN ? ELSE status END,checked=?,delivered=COALESCE(delivered,?),detail=? WHERE order_id=? AND awb=?').bind(status,now,delivered?now:null,JSON.stringify((t.shipment_track_activities||[]).slice(0,30)),id,s.awb),db.prepare("UPDATE orders SET status=CASE WHEN ?='Delivered' THEN 'Delivered' WHEN ?='Shipped' THEN 'Shipped' ELSE status END WHERE id=? AND status IN ('Confirmed','Shipped') AND EXISTS(SELECT 1 FROM shipments WHERE order_id=? AND awb=?)").bind(delivered?'Delivered':'', [6,17,18,38].includes(code)?'Shipped':'',id,id,s.awb)]);
}
export async function payoutPreview(id:string){const db=database();const order=await db.prepare('SELECT o.*,p.payment_id,p.state AS attempt_state FROM orders o LEFT JOIN payment_attempts p ON p.id=o.id WHERE o.id=?').bind(id).first<any>();if(!order)throw Error('Order not found');const allocations=(await db.prepare('SELECT a.*,r.name FROM allocations a JOIN artists r ON r.id=a.artist_id WHERE order_id=?').bind(id).all<any>()).results;
 const groups=new Map<string,number>();for(const a of allocations)groups.set(a.account,(groups.get(a.account)||0)+a.net);
 const items=Array.from(groups,([account,amount])=>({account,amount,currency:'INR'})).filter(i=>i.amount>0);const delivered=await db.prepare("SELECT MAX(created) AS at FROM order_events WHERE order_id=? AND status='Delivered'").bind(id).first<any>();const ret=await db.prepare("SELECT id FROM returns WHERE order_id=? AND status<>'Declined'").bind(id).first();const hold=Number(runtime().ARTIST_HOLD_DAYS);const eligibleAt=delivered?.at&&Number.isInteger(hold)&&hold>=1?delivered.at+hold*86400000:null;
 const blocked=!integrationStatus().payouts?'Route transfers are not activated':order.payment_method!=='razorpay'||order.payment_status!=='Paid'||order.attempt_state!=='paid'?'Requires a captured Razorpay payment':order.status!=='Delivered'?'Awaiting delivery':ret?'Return requires review; funds remain held':!eligibleAt||eligibleAt>Date.now()?'Delivery inspection period has not ended':!items.length?'No artist earnings assigned to this order':null;
 return {order,allocations,items,eligibleAt,blocked};
}
// Claim once before contacting the provider. Ambiguous responses require read-only reconciliation, never blind retries.
export async function releaseArtists(id:string){const db=database(),p=await payoutPreview(id);if(p.blocked)throw Error(p.blocked);const payment=await gateway('payments/'+p.order.payment_id);if(payment.status!=='captured'||payment.currency!=='INR'||payment.amount!==p.order.total||Number(payment.amount_refunded)!==0)throw Error('Payment is not eligible for transfer');
 const payload={transfers:p.items.map(i=>({...i,notes:{artelier_order:id}}))};const claimed=await db.prepare("INSERT INTO transfers(order_id,state,payload,created,updated) SELECT ?,'submitting',?,?,? WHERE EXISTS(SELECT 1 FROM orders WHERE id=? AND status='Delivered' AND payment_status='Paid') AND NOT EXISTS(SELECT 1 FROM returns WHERE order_id=? AND status<>'Declined') ON CONFLICT(order_id) DO NOTHING RETURNING order_id").bind(id,JSON.stringify(payload),Date.now(),Date.now(),id,id).first();if(!claimed)throw Error('Already submitted or no longer eligible. Refresh transfer status.');
 try{const result=await gateway('payments/'+p.order.payment_id+'/transfers',payload);await db.prepare("UPDATE transfers SET state='submitted',result=?,updated=? WHERE order_id=?").bind(JSON.stringify(result),Date.now(),id).run();}catch{await db.prepare("UPDATE transfers SET state='review',updated=? WHERE order_id=?").bind(Date.now(),id).run();throw Error('Provider outcome uncertain. Refresh transfer status; do not submit again.');}
}
export async function reconcileArtists(id:string){const db=database(),p=await payoutPreview(id);if(!p.order.payment_id)throw Error('No Razorpay payment');const row=await db.prepare('SELECT * FROM transfers WHERE order_id=?').bind(id).first<any>();if(!row)throw Error('No transfer submitted');const result=await gateway('payments/'+p.order.payment_id+'/transfers');const expected=JSON.parse(row.payload).transfers;const actual=result.items||[];const matching=expected.every((e:any)=>actual.filter((a:any)=>a.recipient===e.account&&a.amount===e.amount&&a.notes?.artelier_order===id&&a.currency==='INR'&&!a.amount_reversed).length===1)&&actual.filter((a:any)=>a.notes?.artelier_order===id).length===expected.length;await db.prepare('UPDATE transfers SET state=?,result=?,updated=? WHERE order_id=?').bind(matching?'submitted':'review',JSON.stringify(result),Date.now(),id).run();
}
