import {database,runtime} from './shop';
import {z} from 'zod';
export const purchaseSchema=z.object({key:z.string().uuid(),customer:z.object({name:z.string().trim().min(2).max(100),email:z.string().email().max(150),phone:z.string().regex(/^[+0-9 ()-]{8,20}$/),address:z.string().trim().min(10).max(500),city:z.string().trim().min(2).max(80),pin:z.string().regex(/^[0-9]{6}$/)}),items:z.array(z.object({id:z.string().max(80),qty:z.number().int().min(1).max(99)})).min(1).max(40)});
export function onlineReady(){const e=runtime();return e.ENABLE_ONLINE_PAYMENTS==='true'&&!!e.RAZORPAY_KEY_ID&&!!e.RAZORPAY_KEY_SECRET&&!!e.RAZORPAY_WEBHOOK_SECRET;}
export function sessionId(r:Request){return r.headers.get('cookie')?.match(/(?:^|; )art_cart=([a-f0-9-]{36})(?:;|$)/)?.[1]||null;}
export async function gateway(path:string,body?:unknown){const e=runtime();if(!e.RAZORPAY_KEY_ID||!e.RAZORPAY_KEY_SECRET)throw Error('Payments are not configured');const r=await fetch('https://api.razorpay.com/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:'Basic '+btoa(e.RAZORPAY_KEY_ID+':'+e.RAZORPAY_KEY_SECRET),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Payment provider unavailable. Please try again.');return await r.json() as any;}
// Each release is a guarded atomic batch: repeat calls cannot restore stock twice.
export async function expireReservations(){const db=database();const rows=(await db.prepare("SELECT * FROM payment_attempts WHERE state='pending' AND expires<? LIMIT 20").bind(Date.now()).all<any>()).results;for(const a of rows){const items=JSON.parse(a.items);await db.batch([db.prepare("UPDATE payment_attempts SET state='releasing' WHERE id=? AND state='pending' AND expires<?").bind(a.id,Date.now()),...items.map((i:any)=>db.prepare("UPDATE products SET stock=stock+? WHERE id=? AND EXISTS(SELECT 1 FROM payment_attempts WHERE id=? AND state='releasing')").bind(i.qty,i.id,a.id)),db.prepare("UPDATE payment_attempts SET state='expired' WHERE id=? AND state='releasing'").bind(a.id)]);}}
export async function createCheckout(raw:unknown,session:string){const b=purchaseSchema.parse(raw);if(new Set(b.items.map(i=>i.id)).size!==b.items.length)throw Error('Duplicate products');await expireReservations();const db=database();const existing=await db.prepare('SELECT * FROM payment_attempts WHERE id=?').bind(b.key).first<any>();if(existing){if(existing.session!==session)throw Error('Invalid checkout');if(existing.state!=='pending')return {state:existing.state,id:existing.id};return checkoutResponse(existing);}
if(await db.prepare('SELECT id FROM orders WHERE id=?').bind(b.key).first())throw Error('This checkout has already been used. Please reload the shop.');
const active=await db.prepare("SELECT count(*) AS n FROM payment_attempts WHERE session=? AND state='pending'").bind(session).first<any>();if(active.n>=3)throw Error('Please finish an existing checkout or wait 30 minutes before starting another.');const lines=[];for(const i of b.items){const p=await db.prepare('SELECT * FROM products WHERE id=? AND active=1').bind(i.id).first<any>();if(!p||p.stock<i.qty)throw Error('An item is unavailable in this quantity. Please update your bag.');lines.push({id:p.id,name:p.name,price:p.price,qty:i.qty});}const total=lines.reduce((n,i)=>n+i.price*i.qty,0);const provider=await gateway('orders',{amount:total,currency:'INR',receipt:b.key,partial_payment:false});if(!/^order_[a-zA-Z0-9]+$/.test(provider.id)||provider.amount!==total||provider.currency!=='INR')throw Error('Invalid payment provider response');const a={id:b.key,session,provider_order:provider.id,customer:JSON.stringify(b.customer),items:JSON.stringify(lines),total,expires:Date.now()+30*60000};
try{await db.batch([db.prepare('INSERT INTO payment_attempts(id,session,provider_order,customer,items,total,state,expires,created) VALUES(?,?,?,?,?,?,\'pending\',?,?)').bind(a.id,session,a.provider_order,a.customer,a.items,total,a.expires,Date.now()),...lines.map(i=>db.prepare('UPDATE products SET stock=stock-? WHERE id=?').bind(i.qty,i.id))]);}catch(e){const retry=await db.prepare('SELECT * FROM payment_attempts WHERE id=? AND session=?').bind(b.key,session).first<any>();if(retry?.state==='pending')return checkoutResponse(retry);throw Error('Stock changed while starting checkout. Please refresh your bag.');}return checkoutResponse(a);}
function checkoutResponse(a:any){return {id:a.id,key:runtime().RAZORPAY_KEY_ID,providerOrder:a.provider_order,amount:a.total,currency:'INR',expires:a.expires,state:'pending',test:String(runtime().RAZORPAY_KEY_ID).startsWith('rzp_test_')};}
// Only a provider API-confirmed captured payment can become a paid order.
export async function confirmPayment(paymentId:string){if(!/^pay_[a-zA-Z0-9]+$/.test(paymentId))throw Error('Invalid payment');const p=await gateway('payments/'+paymentId);const db=database();const a=await db.prepare('SELECT * FROM payment_attempts WHERE provider_order=?').bind(p.order_id).first<any>();if(!a)throw Error('Unknown payment order');if(p.amount!==a.total||p.currency!=='INR')throw Error('Payment amount mismatch');if(a.state==='refunded')return {id:a.id,state:'refunded',total:a.total};if(p.status!=='captured')return {id:a.id,state:'pending'};if(a.state==='paid'||a.state==='refund_required')return {id:a.id,state:a.state,total:a.total};
const lines=JSON.parse(a.items);
try{await db.batch([
 ...lines.map((i:any)=>db.prepare("UPDATE products SET stock=stock-? WHERE id=? AND EXISTS(SELECT 1 FROM payment_attempts WHERE id=? AND state='expired')").bind(i.qty,i.id,a.id)),
 db.prepare("INSERT INTO orders(id,session,customer,items,total,status,payment_method,payment_status,created) SELECT id,session,customer,items,total,'Confirmed','razorpay','Paid',created FROM payment_attempts WHERE id=? AND state IN ('pending','expired') ON CONFLICT(id) DO NOTHING").bind(a.id),
 db.prepare("UPDATE payment_attempts SET state='paid',payment_id=? WHERE id=? AND state IN ('pending','expired')").bind(p.id,a.id)
]);}catch(e){if(!String(e).includes('stock_nonnegative'))throw e;await db.batch([db.prepare("INSERT INTO orders(id,session,customer,items,total,status,payment_method,payment_status,created) SELECT id,session,customer,items,total,'Refund required','razorpay','Paid',created FROM payment_attempts WHERE id=? AND state='expired' ON CONFLICT(id) DO NOTHING").bind(a.id),db.prepare("UPDATE payment_attempts SET state='refund_required',payment_id=? WHERE id=? AND state='expired'").bind(p.id,a.id)]);}
await db.prepare("DELETE FROM carts WHERE id=? AND items=? AND EXISTS(SELECT 1 FROM payment_attempts WHERE id=? AND state='paid')").bind(a.session,JSON.stringify(lines.map((i:any)=>({id:i.id,qty:i.qty}))),a.id).run();
const final=await db.prepare('SELECT state FROM payment_attempts WHERE id=?').bind(a.id).first<any>();return {id:a.id,state:final.state,total:a.total,paymentId:p.id};}
export async function reconcileRefund(paymentId:string){if(!/^pay_[a-zA-Z0-9]+$/.test(paymentId))throw Error('Invalid payment');const p=await gateway('payments/'+paymentId);const db=database();const a=await db.prepare('SELECT * FROM payment_attempts WHERE provider_order=?').bind(p.order_id).first<any>();if(!a)return;if(p.amount_refunded!==a.total)return;const items=JSON.parse(a.items);await db.batch([db.prepare("UPDATE payment_attempts SET state='releasing' WHERE id=? AND state='pending'").bind(a.id),...items.map((i:any)=>db.prepare("UPDATE products SET stock=stock+? WHERE id=? AND EXISTS(SELECT 1 FROM payment_attempts WHERE id=? AND state='releasing')").bind(i.qty,i.id,a.id)),db.prepare("UPDATE orders SET status='Refunded',payment_status='Refunded' WHERE id=?").bind(a.id),db.prepare("UPDATE payment_attempts SET state='refunded',payment_id=? WHERE id=?").bind(paymentId,a.id)]);}
