import {z} from 'zod';
export async function sellerData(db:D1Database,userId:string){const seller=await db.prepare('SELECT * FROM sellers WHERE user_id=?').bind(userId).first();const products=(await db.prepare('SELECT p.* FROM products p JOIN seller_products s ON s.product_id=p.id WHERE s.user_id=? ORDER BY p.created DESC').bind(userId).all()).results;return {seller,products};}
export async function sellerAction(db:D1Database,user:{userId:string,email:string},b:any){
 const now=Date.now();
 if(b.action==='apply'){const v=z.object({name:z.string().trim().min(2).max(100),bio:z.string().trim().min(20).max(2000),portfolio:z.string().url().max(500).refine(s=>new URL(s).protocol==='https:')}).parse(b);const result=await db.prepare("INSERT INTO sellers(user_id,name,email,bio,portfolio,status,created,updated) VALUES(?,?,?,?,?,'Pending',?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,bio=excluded.bio,portfolio=excluded.portfolio,email=excluded.email,status='Pending',reply='',updated=excluded.updated WHERE sellers.status='Rejected'").bind(user.userId,v.name,user.email,v.bio,v.portfolio,now,now).run();if(!result.meta.changes)throw Error('An application already exists. Check its status.');return;}
 if(b.action!=='product')throw Error('Unknown action');
 const seller=await db.prepare("SELECT artist_id FROM sellers WHERE user_id=? AND status='Approved'").bind(user.userId).first<any>();if(!seller?.artist_id)throw Error('Approved seller access required');
 const p=z.object({id:z.string().uuid().optional(),name:z.string().trim().min(2).max(120),category:z.enum(['Original art','Art prints','Ceramics','Handmade']),description:z.string().trim().min(5).max(3000),price:z.number().int().min(100).max(100000000),stock:z.number().int().min(0).max(100000),image:z.string().max(200)}).parse(b.product);
 if(!await db.prepare('SELECT image FROM seller_uploads WHERE image=? AND user_id=?').bind(p.image,user.userId).first())throw Error('Upload your own artwork image first');
 if(p.id){const r=await db.prepare("UPDATE products SET name=?,category=?,description=?,price=?,stock=?,image=?,active=0 WHERE id=? AND EXISTS(SELECT 1 FROM seller_products sp JOIN sellers s ON s.user_id=sp.user_id WHERE sp.product_id=products.id AND s.user_id=? AND s.status='Approved')").bind(p.name,p.category,p.description,p.price,p.stock,p.image,p.id,user.userId).run();if(!r.meta.changes)throw Error('You can edit only your own products while approved');}
 else{const id=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO products(id,name,category,description,price,stock,image,active,created) SELECT ?,?,?,?,?,?,?,0,? WHERE EXISTS(SELECT 1 FROM sellers WHERE user_id=? AND status='Approved' AND artist_id IS NOT NULL)").bind(id,p.name,p.category,p.description,p.price,p.stock,p.image,now,user.userId),db.prepare('INSERT INTO seller_products(product_id,user_id) SELECT id,? FROM products WHERE id=?').bind(user.userId,id),db.prepare('INSERT INTO product_artists(product_id,artist_id) SELECT p.id,s.artist_id FROM products p,sellers s WHERE p.id=? AND s.user_id=?').bind(id,user.userId)]);}
}
export async function reviewSeller(db:D1Database,b:any){const v=z.object({userId:z.string().min(1).max(200),status:z.enum(['Approved','Rejected','Suspended']),artistId:z.string().uuid().optional(),reply:z.string().trim().min(5).max(1000)}).parse(b);const s=await db.prepare('SELECT * FROM sellers WHERE user_id=?').bind(v.userId).first<any>();if(!s)throw Error('Application not found');if(v.status==='Approved'){if(!v.artistId||!await db.prepare('SELECT id FROM artists WHERE id=?').bind(v.artistId).first())throw Error('Create and choose the artist payout profile first');if(s.artist_id&&s.artist_id!==v.artistId)throw Error('Existing artist association cannot be changed here');const used=await db.prepare('SELECT user_id FROM sellers WHERE artist_id=? AND user_id<>?').bind(v.artistId,v.userId).first();if(used)throw Error('Artist profile is already assigned');}
 await db.batch([db.prepare('UPDATE sellers SET status=?,artist_id=COALESCE(artist_id,?),reply=?,updated=? WHERE user_id=?').bind(v.status,v.status==='Approved'?v.artistId!:null,v.reply,Date.now(),v.userId),db.prepare("UPDATE products SET active=0 WHERE id IN (SELECT product_id FROM seller_products WHERE user_id=?) AND EXISTS(SELECT 1 FROM sellers WHERE user_id=? AND status<>'Approved')").bind(v.userId,v.userId)]);
}
