import { sqliteTable, text, integer, check, index } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const products=sqliteTable('products',{id:text('id').primaryKey(),name:text('name').notNull(),category:text('category').notNull(),description:text('description').notNull(),price:integer('price').notNull(),stock:integer('stock').notNull(),image:text('image').notNull(),active:integer('active').notNull().default(1),created:integer('created').notNull()},t=>[check('stock_nonnegative',sql`${t.stock} >= 0`),check('price_positive',sql`${t.price} > 0`),index('products_active_created').on(t.active,t.created)]);
export const carts=sqliteTable('carts',{id:text('id').primaryKey(),items:text('items').notNull(),updated:integer('updated').notNull()});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),session:text('session').notNull(),customer:text('customer').notNull(),items:text('items').notNull(),total:integer('total').notNull(),status:text('status').notNull().default('Pending'),paymentMethod:text('payment_method').notNull().default('cod'),paymentStatus:text('payment_status').notNull().default('unpaid'),gatewayOrderId:text('gateway_order_id'),paymentSessionId:text('payment_session_id'),gatewayPaymentId:text('gateway_payment_id'),stockReleased:integer('stock_released').notNull().default(0),paidAt:integer('paid_at'),carrier:text('carrier'),trackingNumber:text('tracking_number'),trackingUrl:text('tracking_url'),created:integer('created').notNull()},t=>[index('orders_session_created').on(t.session,t.created),index('orders_gateway').on(t.gatewayOrderId),index('orders_created').on(t.created),index('orders_payment_status').on(t.paymentStatus,t.created)]);
export const limits=sqliteTable('limits',{id:text('id').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const paymentAttempts=sqliteTable('payment_attempts',{id:text('id').primaryKey(),session:text('session').notNull(),providerOrder:text('provider_order').notNull().unique(),paymentId:text('payment_id'),customer:text('customer').notNull(),items:text('items').notNull(),total:integer('total').notNull(),state:text('state').notNull().default('pending'),expires:integer('expires').notNull(),created:integer('created').notNull()},t=>[index('attempts_state_expires').on(t.state,t.expires),index('attempts_session_created').on(t.session,t.created)]);

export const orderEvents=sqliteTable('order_events',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),status:text('status').notNull(),created:integer('created').notNull()},t=>[index('events_order_created').on(t.orderId,t.created)]);
export const jobs=sqliteTable('jobs',{id:text('id').primaryKey(),kind:text('kind').notNull(),payload:text('payload').notNull(),state:text('state').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),available:integer('available').notNull(),leaseUntil:integer('lease_until').notNull().default(0),leaseToken:text('lease_token'),lastError:text('last_error'),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('jobs_ready').on(t.state,t.available),index('jobs_lease').on(t.state,t.leaseUntil)]);
