import { sqliteTable, text, integer, check, index } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const products=sqliteTable('products',{id:text('id').primaryKey(),name:text('name').notNull(),category:text('category').notNull(),description:text('description').notNull(),price:integer('price').notNull(),stock:integer('stock').notNull(),image:text('image').notNull(),active:integer('active').notNull().default(1),created:integer('created').notNull()},t=>[check('stock_nonnegative',sql`${t.stock} >= 0`),check('price_positive',sql`${t.price} > 0`),index('products_active_created').on(t.active,t.created)]);
export const carts=sqliteTable('carts',{id:text('id').primaryKey(),items:text('items').notNull(),updated:integer('updated').notNull()});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),session:text('session').notNull(),customer:text('customer').notNull(),items:text('items').notNull(),total:integer('total').notNull(),status:text('status').notNull().default('Pending'),paymentMethod:text('payment_method').notNull().default('cod'),paymentStatus:text('payment_status').notNull().default('unpaid'),gatewayOrderId:text('gateway_order_id'),paymentSessionId:text('payment_session_id'),gatewayPaymentId:text('gateway_payment_id'),stockReleased:integer('stock_released').notNull().default(0),paidAt:integer('paid_at'),carrier:text('carrier'),trackingNumber:text('tracking_number'),trackingUrl:text('tracking_url'),created:integer('created').notNull()},t=>[index('orders_session_created').on(t.session,t.created),index('orders_gateway').on(t.gatewayOrderId),index('orders_created').on(t.created),index('orders_payment_status').on(t.paymentStatus,t.created)]);
export const limits=sqliteTable('limits',{id:text('id').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const paymentAttempts=sqliteTable('payment_attempts',{id:text('id').primaryKey(),session:text('session').notNull(),providerOrder:text('provider_order').notNull().unique(),paymentId:text('payment_id'),customer:text('customer').notNull(),items:text('items').notNull(),total:integer('total').notNull(),state:text('state').notNull().default('pending'),expires:integer('expires').notNull(),created:integer('created').notNull()},t=>[index('attempts_state_expires').on(t.state,t.expires),index('attempts_session_created').on(t.session,t.created)]);

export const orderEvents=sqliteTable('order_events',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),status:text('status').notNull(),created:integer('created').notNull()},t=>[index('events_order_created').on(t.orderId,t.created)]);
export const jobs=sqliteTable('jobs',{id:text('id').primaryKey(),kind:text('kind').notNull(),payload:text('payload').notNull(),state:text('state').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),available:integer('available').notNull(),leaseUntil:integer('lease_until').notNull().default(0),leaseToken:text('lease_token'),lastError:text('last_error'),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('jobs_ready').on(t.state,t.available),index('jobs_lease').on(t.state,t.leaseUntil)]);

export const orderOwners=sqliteTable('order_owners',{orderId:text('order_id').primaryKey(),userId:text('user_id').notNull()},t=>[index('owners_user').on(t.userId)]);
export const addresses=sqliteTable('addresses',{id:text('id').primaryKey(),userId:text('user_id').notNull(),label:text('label').notNull(),details:text('details').notNull(),updated:integer('updated').notNull()},t=>[index('addresses_user').on(t.userId)]);
export const wishlist=sqliteTable('wishlist',{id:text('id').primaryKey(),userId:text('user_id').notNull(),productId:text('product_id').notNull(),created:integer('created').notNull()},t=>[index('wishlist_user').on(t.userId,t.created)]);
export const reviews=sqliteTable('reviews',{id:text('id').primaryKey(),userId:text('user_id').notNull(),orderId:text('order_id').notNull(),productId:text('product_id').notNull(),rating:integer('rating').notNull(),name:text('name').notNull(),title:text('title').notNull(),body:text('body').notNull(),status:text('status').notNull().default('Pending'),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[check('rating_range',sql`${t.rating} >= 1 AND ${t.rating} <= 5`),index('reviews_product_status').on(t.productId,t.status,t.created),index('reviews_user').on(t.userId)]);
export const returns=sqliteTable('returns',{id:text('id').primaryKey(),orderId:text('order_id').notNull().unique(),userId:text('user_id').notNull(),reason:text('reason').notNull(),details:text('details').notNull(),status:text('status').notNull().default('Requested'),reply:text('reply').notNull().default(''),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('returns_user').on(t.userId,t.created),index('returns_status').on(t.status,t.created)]);

export const artists=sqliteTable('artists',{id:text('id').primaryKey(),name:text('name').notNull(),account:text('account').notNull(),commissionBps:integer('commission_bps').notNull(),created:integer('created').notNull()},t=>[check('commission_range',sql`${t.commissionBps} >= 0 AND ${t.commissionBps} <= 10000`)]);
export const productArtists=sqliteTable('product_artists',{productId:text('product_id').primaryKey(),artistId:text('artist_id').notNull()});
export const allocations=sqliteTable('allocations',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),productId:text('product_id').notNull(),artistId:text('artist_id').notNull(),account:text('account').notNull(),gross:integer('gross').notNull(),net:integer('net').notNull(),commissionBps:integer('commission_bps').notNull()},t=>[index('allocations_order').on(t.orderId)]);
export const transfers=sqliteTable('transfers',{orderId:text('order_id').primaryKey(),state:text('state').notNull(),payload:text('payload').notNull(),result:text('result'),created:integer('created').notNull(),updated:integer('updated').notNull()});
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),status:text('status').notNull(),customer:text('customer').notNull(),state:text('state').notNull().default('pending'),payload:text('payload'),providerId:text('provider_id'),firstAttempt:integer('first_attempt'),created:integer('created').notNull()},t=>[index('notifications_state').on(t.state,t.created)]);
export const shipments=sqliteTable('shipments',{orderId:text('order_id').primaryKey(),awb:text('awb').notNull().unique(),status:text('status').notNull().default('Awaiting tracking'),checked:integer('checked').notNull().default(0),delivered:integer('delivered'),detail:text('detail')});

export const sellers=sqliteTable('sellers',{userId:text('user_id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),bio:text('bio').notNull(),portfolio:text('portfolio').notNull(),status:text('status').notNull().default('Pending'),artistId:text('artist_id').unique(),reply:text('reply').notNull().default(''),created:integer('created').notNull(),updated:integer('updated').notNull()});
export const sellerProducts=sqliteTable('seller_products',{productId:text('product_id').primaryKey(),userId:text('user_id').notNull()},t=>[index('seller_products_user').on(t.userId)]);
export const sellerUploads=sqliteTable('seller_uploads',{image:text('image').primaryKey(),userId:text('user_id').notNull()});
